### ISSUE TITLE
Deep Learning Plugin Selection

### ISSUE THREAD

**Issue by oreillyp** [hugofloresgarcia/audacity#101]
### Bug description

When selecting a Deep Learning Effect that has not been installed, Audacity will silently fall back to the most recently selected/installed Deep Learning Effect and apply it.

### Steps to reproduce

Install and select a Deep Learning Effect, and apply it to audio. Then, select a separate Deep Learning Effect that has not yet been installed and attempt to apply it to audio; Audacity will apply the first effect without raising any warning that the currently selected effect has not been installed.

### Expected behavior

Audacity should notify the user that the selected effect has not been installed, and should not apply an effect.

### Audacity Version

other

### Operating system

macOS

### Additional context

Bug encountered on 3.1 build on M1 MacBook.

**Comment by aldo-aguilar** [comment]
`rebase-3.2.3` has solved this issue
