### ISSUE TITLE
Separate Effects from Analyzing 

### ISSUE THREAD

**Issue by tin2tin** [hugofloresgarcia/audacity#67]
**Is your feature request related to a problem? Please describe.**
Trying to add and install ex. label related models will fail in Effects popup, but will install succesfully in Analyze popup, so when looking up models, only those compatible to the current popup should show.

**Comment by hugofloresgarcia** [comment]
Could you explain a bit more? Are you trying to import a labeler model inside Deep Learning Effect, and it's failing?

**Comment by hugofloresgarcia** [comment]
closing this, as it will get fixed whenever #76 gets fixed
