### ISSUE TITLE
Video shown on installation is for Audacity 3.1  not Audacity 3.2

### ISSUE THREAD

**Issue by bryan-pardo** [hugofloresgarcia/audacity#78]
**Describe the bug**
One fix to this would be to fix the video that is shown on startup when you first install. Right now, when you first install, you get a help page that says "what's new in Audacity 3.2.xxxx" with a link to a video for Audacity 3.1.   It might be good to have a link to a video for how to use the features we introduce in 3.2.

**To Reproduce**
1. Install Audacity.
2. Start it up for the 1st time
3. The video that comes up in the dialog box that says "whats new in audacity 3.2.xxxx" is one that describes new features in Audacity 3.1, not the new deep learning tools in 3.2. Here's the video linkhttps://www.youtube.com/watch?v=HpA138b-J9s

**Expected behavior**
The video that comes up should be a quick video on how to use the deep learning tools, not on the new features from release 3.1

**Screenshots**

**Additional information (please complete the following information):**
 - OS: [e.g. Mac High Sierra, Ubuntu 18.04, Windows 10]
 - Version [e.g. Audacity 2.5.1]
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**

**Comment by hugofloresgarcia** [comment]
The video itself is left to the Audacity people to manage. We can add a temporary message to the Help Text to introduce the deep learning tools: a393d7f00fded9386b34131c8d28a7d1e600d06d.
