### ISSUE TITLE
Example model download reports failure 

### ISSUE THREAD

**Issue by bryan-pardo** [hugofloresgarcia/audacity#79]
**Describe the bug**
Example model download fails and reports error. See attached screen shots.

**To Reproduce**
1. Go to  Analyze/Deep Learning Analyzer (or to Effect/Deep Learning Effect)
2. When the Deep-learning-Effect (or Deep-learning-Analyzer) dialog box opens, click "Add from Hugging Face"
3. When the AddRepo dialog opens, enter the exact string given as an example repoID "huggof/ConvTasNet-DAMP-Vocals" & click "OK".
4. See error dialog (I'd upload a screenshot, but it's not letting me for some reason)

**Expected behavior**
The example repoID would load nicely and not report an error.

**Screenshots**

**Additional information (please complete the following information):**
 - OS: MacOS 11.6 Big Sur
 - Version Audacity 3.2.0-alpha20211105
 
**Additional context**
Weirdly, this repo is one of your curated repos and seems to install fine when I click on this curated repository list in the Dee-learning-Effect dialog. So maybe you report an error when the repository is already loaded? Or when it is a curated one?  Either way this needs fixing, since the example  you provide should NOT be the thing that breaks the system.

**Comment by hugofloresgarcia** [comment]
Linking this to #76
