### ISSUE TITLE
Model load error for new VAD model

### ISSUE THREAD

**Issue by bryan-pardo** [hugofloresgarcia/audacity#80]
**Describe the bug**
Aldo's new VAD: I loaded it. When I went to select it, I got this model loading error.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional information (please complete the following information):**
 - MacOS 11.6
 - audacity 3.2.0-alpha-20211105
 - (if relevant) Sound Device [e.g. Windows WASAPI, USB Sound card]

**Additional context**
[VAD-error-on-model-load.txt](https://github.com/hugofloresgarcia/audacity/files/7571731/VAD-error-on-model-load.txt)

**Comment by hugofloresgarcia** [comment]
the VAD model is not out yet, so I'm closing this until we have it on the list of builtins
