### ISSUE TITLE
Issue template needed for workflow improvements

### ISSUE THREAD

**Issue by cwitkowitz** [hugofloresgarcia/audacity#83]
**Is your feature request related to a problem? Please describe.**
We discussed three distinct types of issues in our meeting on 11/7/2022: bugs, feature requests, and workflow improvements. The first two are already covered nicely by pre-existing issue templates, but there is no issue template for the third.

**Describe the solution you'd like**
Add a new Markdown entry for "Workflow improvement" under `.github/ISSUE_TEMPLATE/`.

**Describe alternatives you've considered**
We could alternatively consider workflow improvements as feature requests and use labels to identify these issues.

**Additional context**
N/A

**Comment by hugofloresgarcia** [comment]
closing this, since we're moving away from making a built-in audacity effect and moving towards a more cross-platform solution
