### ISSUE TITLE
Crash when adding non-existent model from Hugging Face

### ISSUE THREAD

**Issue by cwitkowitz** [hugofloresgarcia/audacity#86]
**Describe the bug**
When I attempt to add a model from Hugging Face that does not exist, audacity crashes with the following error message:
```
21:58:21: Debug: Fetching model card from https://huggingface.co/non-existent-model/resolve/main/metadata.json
21:58:21: Debug: Got reponse with HTTP code: 401
Segmentation fault (core dumped)
```
I've also seen it crash with `HTTP code: 404`.

**To Reproduce**
1. In the "Deep Learning Effect" window, click "Add From Hugging Face"
2. Type "non-existent-model" and click "OK"

**Expected behavior**
I would expect an error message stating that the specified model does not exist. Upon closing this message, I would then expect to be returned to the "AddRepo" window to try again.

**Additional information:**
 - OS: Ubuntu 18.04
 - Version v3.2.0-alpha

**Comment by cwitkowitz** [comment]
This issue seems to stem from the `wxLogError(e.what())` call for `ModelManagerException` in `DeepModelManager.cpp`.

The message returned when calling `e.m_msg.Translation.c_str()` looks fine. However, when `e.what()` is called directly, even though the function only runs `return m_msg.Translation.c_str()`, nonsense is returned.

**Comment by aldo-aguilar** [comment]
closing this as it's addressed in the [PR for issue 96](https://github.com/audacitorch/audacity/pull/97)
