### ISSUE TITLE
Model not added

### ISSUE THREAD

**Issue by cwitkowitz** [hugofloresgarcia/audacity#87]
**Describe the bug**
Nothing happens after adding an audacity model from Hugging Face.

**To Reproduce**
1. In the "Deep Learning Effect" window, click "Add From Hugging Face"
2. Type "aguilara42/openl3-labeler-w-timestamps" and click "OK"

**Expected behavior**
I would expect some sort of progress bar to show the model is downloading and then a message stating the download was successful when this is complete. I should then be able to see the new model in the "Deep Learning Effect" window.

**Additional information:**
 - OS: Ubuntu 18.04
 - Version v3.2.0-alpha

**Comment by cwitkowitz** [comment]
I believe this happened because the chosen model is considered an analyzer model rather than an effect. So, it should have been opened in the "Deep Learning Analyzer" window. Still, I think there should be some user-facing error message.

**Comment by aldo-aguilar** [comment]
closing due to duplicate with issue #76

**Comment by aldo-aguilar** [comment]
closing due to duplicate with issue #76
