### ISSUE TITLE
Error Message Thrown When Opening Deep Learning Analyzer Menu

### ISSUE THREAD

**Issue by aldo-aguilar** [hugofloresgarcia/audacity#88]
**Describe the bug**
An error message will appear when you initially open up a menu for the deep learning labeler.

**To Reproduce**
1. Go to 'Analyze'
2. Click on 'Deep Learning'
3. See error

**Expected behavior**
The menu should open up without an initial error message.

**Additional context**
this happened on MacOS

**Comment by hugofloresgarcia** [comment]
can't repro @aldo-aguilar. @oreillyp can you try?

**Comment by oreillyp** [comment]
Also couldn't repo on OS 13.0 / M1 MacBook

**Comment by hugofloresgarcia** [comment]
closing!
