### ISSUE TITLE
DeepModel:: BuiltInModulesDir() platform agnostic 

### ISSUE THREAD

**Issue by aldo-aguilar** [hugofloresgarcia/audacity#93]
### Your idea

Currently in the `rebase-3.2` branch we're using two different `FileName` directory functions for locating the "deeplearning-models" module dir.

We want to verify if it's possible to use this line
` return FileNames::MkDir( wxFileName( FileNames::ResourcesDir(), wxT("deeplearning-models") ).GetFullPath() ); `
for mac and windows. This line is NEEDED for linux and the the `FileNames::BaseDir()` will not work for finding the model card schema. 

### Problem to be solved

Test if `FileNames::ResourcesDir()` will work for windows and mac.

### Additional context

related to [PR 92](https://github.com/audacitorch/audacity/pull/92/files/329faef2b5f916ac6d7739a2bdeb9988f48850b7#diff-cd76ea0e747920fd90204fb77161a97ffd0cd04fbeca4d4d16cdee17012d5d96)

**Comment by hugofloresgarcia** [comment]
@aldo-aguilar I take it this was already addressed in #92 ?

**Comment by hugofloresgarcia** [comment]
if so let's close this

**Comment by aldo-aguilar** [comment]
this is an optional improvement
